import { test, expect } from '@playwright/test'

test('loads the All tasks workspace by default', async ({ page }) => { await page.goto('/'); await expect(page.getByRole('heading', { name: 'All tasks' })).toBeVisible(); const views = page.getByRole('navigation', { name: 'Smart views' }).getByRole('button'); await expect(views.first()).toContainText('All tasks') })
test('creates and edits a task', async ({ page }) => { await page.goto('/'); await page.getByRole('textbox', { name: 'Add a task' }).fill('E2E task'); await page.getByRole('textbox', { name: 'Add a task' }).press('Enter'); await expect(page.getByRole('textbox', { name: 'Task details' })).toHaveValue('E2E task') })
test('completes and undoes a task', async ({ page }) => { await page.goto('/'); const button = page.getByRole('button', { name: 'Complete Book dentist appointment' }); await button.click(); await expect(page.getByText('Task completed')).toBeVisible(); await page.getByRole('button', { name: 'Undo' }).click(); await expect(page.getByRole('button', { name: 'Complete Book dentist appointment' })).toBeVisible() })
test('searches tasks', async ({ page }) => { await page.goto('/'); await page.keyboard.press('/'); const dialog = page.getByRole('dialog', { name: 'Search tasks' }); await dialog.getByPlaceholder('Search title, notes, or list…').fill('dentist'); await expect(dialog.getByText('Book dentist appointment')).toBeVisible() })
test('supports dark mode', async ({ page }) => { await page.goto('/'); await page.getByRole('button', { name: 'Settings' }).click(); await page.getByLabel('Theme').selectOption('dark'); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark') })
test('uses dedicated mobile navigation', async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/'); const nav = page.getByRole('navigation', { name: 'Mobile navigation' }); await expect(nav).toBeVisible(); const today = nav.getByRole('button', { name: 'Today' }); await today.click(); await expect(today).toHaveClass(/active/) })
test('switches to Hungarian', async ({ page }) => { await page.goto('/'); await page.getByRole('button', { name: 'Settings' }).click(); await page.getByLabel('Language').selectOption('hu'); await expect(page.getByRole('heading', { name: 'Összes feladat' })).toBeVisible(); await expect(page.locator('html')).toHaveAttribute('lang', 'hu') })
test('reorders tasks with drag and drop', async ({ page }) => { await page.goto('/'); const source = page.getByRole('button', { name: 'Reorder Review Q4 product brief' }); const target = page.getByRole('button', { name: 'Reorder Send updated launch timeline' }); const from = await source.boundingBox(); const to = await target.boundingBox(); if (!from || !to) throw new Error('Drag handles are not visible'); await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2); await page.mouse.down(); await page.mouse.move(from.x + from.width / 2 + 12, from.y + from.height / 2 + 12, { steps: 4 }); await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 12 }); await page.mouse.up(); await expect.poll(async () => { const rows = await page.getByRole('region', { name: 'Tasks' }).locator('article strong').allTextContents(); return rows.indexOf('Review Q4 product brief') > rows.indexOf('Send updated launch timeline') }).toBe(true) })
