export type AppLocale = 'en' | 'hu'

const en = {
  all: 'All tasks', today: 'Today', upcoming: 'Upcoming', noDate: 'No date', completed: 'Completed', assigned: 'Assigned', myLists: 'My lists', settings: 'Settings', demo: 'Demo workspace', googleTasks: 'Google Tasks', reconnectGoogle: 'Reconnect Google', synced: 'Synced just now', syncing: 'Syncing…', offline: 'Offline', reconnectRequired: 'Reconnect required', syncError: 'Sync error',
  focusOne: '1 task to focus on', focusMany: '{count} tasks to focus on', nothingToday: 'Nothing due today.', noTasksHere: 'No tasks here.', addTask: 'Add a task…', createListFirst: 'Create a list first', date: 'Date', tasks: 'tasks', search: 'Search', searchTasks: 'Search tasks', searchPlaceholder: 'Search title, notes, or list…', filterTasks: 'Filter tasks…', clearFilter: 'Clear filter',
  cachedReadonly: 'Cached tasks are read-only.', reconnect: 'Reconnect Google', offlineCached: 'You’re offline. Cached tasks remain available.', syncErrorDetail: 'Google Tasks could not be synchronized.', retry: 'Try again', syncLoadingLists: 'Loading task lists…', syncProgress: '{count} tasks downloaded · {done}/{total} lists complete', syncSaving: 'Saving the synchronized tasks…', taskDetails: 'Task details', toggleCompletion: 'Toggle completion', dueDate: 'Due date', list: 'List', links: 'Links', link: 'Link', openEmail: 'Open attached email', notes: 'Notes', addNotes: 'Add notes…', subtasks: 'Subtasks', of: 'of', addSubtask: 'Add subtask', deleteTask: 'Delete task', updated: 'Updated', savedGoogle: 'Saved in Google Tasks', openGoogle: 'Open in Google Tasks', openSource: 'Open source', assignedFrom: 'Assigned from',
  noSearch: 'No tasks match your search.', everyHasDate: 'Every task has a date.', noCompleted: 'No completed tasks.', noTasks: 'No tasks yet.', addATask: 'Add a task', commandMenu: 'Command menu', commandPlaceholder: 'Type a command…', goToday: 'Go to Today', goUpcoming: 'Go to Upcoming', createTask: 'Create task', refreshTasks: 'Refresh tasks', toggleTheme: 'Toggle theme', exportTasks: 'Export tasks', openSettings: 'Open settings', keyboardShortcuts: 'Keyboard shortcuts',
  appearance: 'Appearance', theme: 'Theme', system: 'System', light: 'Light', dark: 'Dark', density: 'Density', comfortable: 'Comfortable', compact: 'Compact', behavior: 'Behavior', upcomingHorizon: 'Upcoming horizon', days: 'days', data: 'Data', refreshNow: 'Refresh now', clearCache: 'Clear local cache', disconnect: 'Disconnect Google', about: 'About', privacy: 'With the authorization backend the Google session lives in a server-side cookie the page cannot read, and the browser only holds a short-lived access token. Without a backend the access token stays in this tab until it expires. Cached task data is stored only on this device.', language: 'Language', english: 'English', hungarian: 'Magyar',
  newTask: 'New task', closePanel: 'Close panel', openSelected: 'Open selected task', toggleSelected: 'Toggle selected task', tasksTab: 'Tasks', todayTab: 'Today', upcomingTab: 'Upcoming', searchTab: 'Search',
  welcomeLead: 'Your Google Tasks, with a better workspace.', welcomePrivacy: 'Your tasks remain in Google Tasks. TaskStride doesn’t require its own task database.', connectGoogle: 'Connect Google Tasks', howItWorks: 'How it works',
  taskCompleted: 'Task completed', taskReopened: 'Task reopened', undo: 'Undo', taskDeleted: 'Task deleted', refreshed: 'Tasks refreshed', exported: 'Export downloaded', cacheCleared: 'Local cache cleared', backOnline: 'Back online', couldNotSave: 'Couldn’t save task', reorderHint: 'Drop onto a list in the sidebar to move a task between lists.', addList: 'Add list', smartViews: 'Smart views', taskLists: 'Task lists', reorder: 'Reorder', complete: 'Complete', markIncomplete: 'Mark incomplete', taskActions: 'Task actions', close: 'Close', mobileNavigation: 'Mobile navigation',
  importTasks: 'Import tasks', importing: 'Importing tasks… {done}/{total}', importDone: '{created} imported · {skipped} already existed', importFailed: '{failed} could not be created', importNothing: 'Every task in this file already exists.', importInvalid: 'This file is not a TaskStride export.', importOffline: 'Reconnect Google to import tasks.', addTaskMobile: 'Show the task composer', hideComposer: 'Hide the task composer',
  edgeSignInRequired: 'Site sign-in expired', edgeSignInDetail: 'The site sign-in has expired, so tasks cannot sync.', edgeSignInAction: 'Sign in again',
  sessionStatus: 'Google session', sessionServer: 'Kept on the server — no hourly sign-in', sessionClient: 'This tab only — expires within an hour', sessionSignedOut: 'Not connected', sessionDemo: 'Demo data',
  editSubtask: 'Edit subtask', deleteSubtask: 'Delete subtask', openSubtask: 'Open subtask', subtaskDeleted: 'Subtask deleted',
}

const hu: Record<keyof typeof en, string> = {
  all: 'Összes feladat', today: 'Ma', upcoming: 'Közelgő', noDate: 'Dátum nélkül', completed: 'Elvégzett', assigned: 'Hozzám rendelt', myLists: 'Saját listák', settings: 'Beállítások', demo: 'Bemutató munkaterület', googleTasks: 'Google Tasks', reconnectGoogle: 'Google újracsatlakoztatása', synced: 'Szinkronizálva', syncing: 'Szinkronizálás…', offline: 'Offline', reconnectRequired: 'Újracsatlakozás szükséges', syncError: 'Szinkronizálási hiba',
  focusOne: '1 feladat vár rád', focusMany: '{count} feladat vár rád', nothingToday: 'Mára nincs esedékes feladat.', noTasksHere: 'Itt nincs feladat.', addTask: 'Feladat hozzáadása…', createListFirst: 'Előbb hozz létre egy listát', date: 'Dátum', tasks: 'feladat', search: 'Keresés', searchTasks: 'Feladatok keresése', searchPlaceholder: 'Keresés címben, jegyzetben vagy listában…', filterTasks: 'Feladatok szűrése…', clearFilter: 'Szűrő törlése',
  cachedReadonly: 'A gyorsítótárazott feladatok csak olvashatók.', reconnect: 'Google újracsatlakoztatása', offlineCached: 'Offline vagy. A mentett feladatok továbbra is elérhetők.', syncErrorDetail: 'A Google Tasks szinkronizálása nem sikerült.', retry: 'Újrapróbálás', syncLoadingLists: 'Feladatlisták betöltése…', syncProgress: '{count} feladat letöltve · {done}/{total} lista kész', syncSaving: 'A szinkronizált feladatok mentése…', taskDetails: 'Feladat részletei', toggleCompletion: 'Elvégzés váltása', dueDate: 'Határidő', list: 'Lista', links: 'Hivatkozások', link: 'Hivatkozás', openEmail: 'Csatolt e-mail megnyitása', notes: 'Jegyzetek', addNotes: 'Jegyzet hozzáadása…', subtasks: 'Részfeladatok', of: '/', addSubtask: 'Részfeladat hozzáadása', deleteTask: 'Feladat törlése', updated: 'Frissítve', savedGoogle: 'Mentve a Google Tasksban', openGoogle: 'Megnyitás a Google Tasksban', openSource: 'Forrás megnyitása', assignedFrom: 'Hozzárendelve innen:',
  noSearch: 'Nincs a keresésnek megfelelő feladat.', everyHasDate: 'Minden feladatnak van dátuma.', noCompleted: 'Nincs elvégzett feladat.', noTasks: 'Még nincs feladat.', addATask: 'Feladat hozzáadása', commandMenu: 'Parancsmenü', commandPlaceholder: 'Írj be egy parancsot…', goToday: 'Ugrás a Mai naphoz', goUpcoming: 'Ugrás a Közelgőkhöz', createTask: 'Feladat létrehozása', refreshTasks: 'Feladatok frissítése', toggleTheme: 'Téma váltása', exportTasks: 'Feladatok exportálása', openSettings: 'Beállítások megnyitása', keyboardShortcuts: 'Billentyűparancsok',
  appearance: 'Megjelenés', theme: 'Téma', system: 'Rendszer', light: 'Világos', dark: 'Sötét', density: 'Sűrűség', comfortable: 'Kényelmes', compact: 'Kompakt', behavior: 'Működés', upcomingHorizon: 'Közelgő időtáv', days: 'nap', data: 'Adatok', refreshNow: 'Frissítés most', clearCache: 'Helyi gyorsítótár törlése', disconnect: 'Google leválasztása', about: 'Névjegy', privacy: 'Az authentikációs backenddel a Google-munkamenet egy szerveroldali cookie-ban van, amit az oldal nem tud kiolvasni, a böngésző csak rövid életű hozzáférési tokent tart. Backend nélkül a hozzáférési token lejáratig ebben a böngészőfülben marad. A gyorsítótárazott feladatadatok kizárólag ezen az eszközön tárolódnak.', language: 'Nyelv', english: 'English', hungarian: 'Magyar',
  newTask: 'Új feladat', closePanel: 'Panel bezárása', openSelected: 'Kijelölt feladat megnyitása', toggleSelected: 'Kijelölt feladat elvégzésének váltása', tasksTab: 'Feladatok', todayTab: 'Ma', upcomingTab: 'Közelgő', searchTab: 'Keresés',
  welcomeLead: 'Google-feladataid egy jobb munkatérben.', welcomePrivacy: 'A feladataid a Google Tasksban maradnak. A TaskStride nem igényel saját feladat-adatbázist.', connectGoogle: 'Google Tasks csatlakoztatása', howItWorks: 'Hogyan működik?',
  taskCompleted: 'Feladat elvégezve', taskReopened: 'Feladat újranyitva', undo: 'Visszavonás', taskDeleted: 'Feladat törölve', refreshed: 'Feladatok frissítve', exported: 'Export letöltve', cacheCleared: 'Helyi gyorsítótár törölve', backOnline: 'Újra online', couldNotSave: 'A feladat mentése sikertelen', reorderHint: 'Másik listába helyezéshez húzd a feladatot az oldalsáv megfelelő listájára.', addList: 'Lista hozzáadása', smartViews: 'Intelligens nézetek', taskLists: 'Feladatlisták', reorder: 'Átrendezés', complete: 'Elvégzés', markIncomplete: 'Visszaállítás elvégzetlenre', taskActions: 'Feladatműveletek', close: 'Bezárás', mobileNavigation: 'Mobil navigáció',
  importTasks: 'Feladatok importálása', importing: 'Importálás… {done}/{total}', importDone: '{created} importálva · {skipped} már megvolt', importFailed: '{failed} nem jött létre', importNothing: 'A fájlban minden feladat már megvan.', importInvalid: 'Ez a fájl nem TaskStride-export.', importOffline: 'Az importáláshoz csatlakozz újra a Google-hoz.', addTaskMobile: 'Feladatbeviteli sáv megjelenítése', hideComposer: 'Feladatbeviteli sáv elrejtése',
  edgeSignInRequired: 'A webhely-bejelentkezés lejárt', edgeSignInDetail: 'A webhelyre való bejelentkezés lejárt, ezért a feladatok nem szinkronizálódnak.', edgeSignInAction: 'Újra bejelentkezés',
  sessionStatus: 'Google-munkamenet', sessionServer: 'Szerveren tárolva — nincs óránkénti bejelentkezés', sessionClient: 'Csak ez a fül — egy órán belül lejár', sessionSignedOut: 'Nincs csatlakoztatva', sessionDemo: 'Bemutató adatok',
  editSubtask: 'Részfeladat szerkesztése', deleteSubtask: 'Részfeladat törlése', openSubtask: 'Részfeladat megnyitása', subtaskDeleted: 'Részfeladat törölve',
}

export const messages = { en, hu }
export type Messages = typeof en
